### ISSUE TITLE
这种验证码无法识别？

### ISSUE THREAD

**Issue by BadDeveloper2022** [by-syk/GraphicCR#1]
data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAA8AKADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigAooooAKKKKACiiigAorl/FXjfT/AAwBFIfNumC7YlwWYlgAqrnczHPRQccFsAjPO2fxUiiuVTVIFijeUQIkeZHZyNwIZRsYc46jBBHJFAHpVFFUrfVrC6vpbGC7ie6iXdJCGG5RxyR+IoAu0Vi+KvElr4U0C41S6UuIlJSJTgyEAnAJ9gT+FQeEfE//AAlPh1dZFqYIJGYxAHduUf1ByD7g0AdDRWDovjbw14gjD6ZrVnOT/B5gV/8Avk4Pr27Gt6gAorzK5+NugjxfB4b0+yvLy6kvVsjMNqRBy+zIOSSAfau81LX9G0ZSdT1WyswOf9IuFQ/qaANGiq9jfWup2MN7ZTpPbTKHjlQ5Vh6irFABRRWb4hg1O68O6hb6NNHBqUsDJbyyMVWNyMBsgEjHXp1oA0qK8I/4Sb4zeDeNX0RNbtE6yxxCQ49cxcj6sta2jftD+HblxDrWn32lTA4Y485FPuRhv/HaAPUtbkuodDvpbF1S6SBmjZl3AEDPSvK/hN8SNb8R+I73RfEMsTXCRlolSMKcg85x7GvSNG8XeHPEiY0rWLK8LDmJJRvx7ofmH4ivn/xCF+HvxxTUUlCWNw4kkZTxtf7y/mKAPe/EHi/T/Dt3ZW92srPdSFFEYztAGSx9gP5GtO51COLSZL5GIjERkDFScDGc4+nNeB6f4i0jxf8AEGbUNR1OwsdPtUlNtNeXCq2WcHC7j/vD6NXofij4g+C5fD9xZW/iPTCdnyqjF+VGV27e+4L7UAeYaVqVrqvju7v9RkE584xRQucs5xuYs3O1FHX1PyjAAA9Q0PxJ4S8W3raZ9nhmKxbCuGMZGQRuA+VTkZGc9sGvE/h/qvh467fPqMOoFixMMdqkly82cDbgf8DOT/fxUfjSaOy8aWuq6Dol/osiyApHdoluxPUAID8oxx6nvyaAPqLxDJNF4fvmt2CzeSwjY9AccdxXg/wQd5PGd5PqDPJPueNHkG4I3PAz8yH5mx7Ejua63ULjx/4l8Ez3k15oVlpksIJW2he5lkTjJJJ2/XA7GvPvhd4aTW9curKfXLpVVyk0dtdvCJVVjlcqAWOAWAz0z6UAem/HPUbeHwRJZySwZmZQ0b8tjPDKM9QRn8qwvDXj/wAM6X8M10mC5uZdRa3bfb2FtI/lSEYGCBtGSAevUn1qD4t+BfC/hnwY1zpGnRQ3xkWMtIzSsyuQC2XJOR2I9TXaeFrBJ/g1EHiCTS2jXEgUYzKvOcfVRQB8r2dxdWerxaqtskSrc5CYKRhs/d9gOn0r6I8T658QrHwNNrl3q+iadB5I8qKzt3mlk3cAFpOAT6gV49HYP4h+G2oauR+90y8IKKOolJbd+BzXaQeIP+E20rwR4cVyZJLsvdJ1wiYwDQB5/wCFPDouPihpmh6kZCHulWfY5Vum4/MOQfevqbTfht4M0lg1r4dsS458ydPObPrufJzXg8SLaftPBMbVGqYA9Ay8fzr6hoAbHGkUaxxoqIowqqMAD2FOoooAKKKKACsjWfC2g+IUK6vpFneHGA8sQLj6N1H4Gqvibxv4e8I2ctxq2oxRunS3Rg0zkjIATr+JwPeuG0q++IXxEvft8E7+FfDTKVjAjV7m4U/xDcOP97gAHjd1oAZqfwD8E3WpQra3V3YOx8w2kdwGDoCN2A+WHUDOTjIrh/iz8N/CfgzRrd9Na5jvJd2zzZt+8grwR24L/iK9YPwh8NMnnPLqr6rncNWa/kN0reobOP0xUuufDDS/Etlpyazf6hdXlim1bvzArOeOWGMdQP1+tAHLfDr4R+GG8MRT61pCXl+ZXzLI74K5+QgA4wVwfxNdzB8OPBdv9zwvpR/66Wyv/wChA10kEEdvCsMShUUYCjoKkoA8kv8A4QeTqt3e6FJb6a9yJE3RRn90kkSr8oDDGJFc4x92TjBUZztN+CTz60L/AFm8nmDStI6eaOpYk9Qc+nG3IIPBXB9sooAppp8UVg1omTHtwqt0XgDAA6DjoPU14NP4D8aeA/FK6n4ZtlvrUSM6xEAgAb41DYxk+WQSfUmvoWigDyCLwN4r8dXlrqHjeWC3ggZWTT4vu8OjHIGc5XzFPP8AdIr042TWXh02NmiyPDamKJWOA5C4Gfqa0aKAPDvhv4Cv9GTxZ4Z1m2kW3vWQWsxX5X2Bjuz05DL+RqP4T/CPX/C/jAazra2yQwROsKpNvYu3GcAYxgnv6V7rRQB5DqXwl1W++MX/AAmEV/ZwWKXdvcLEdzSPsVA4xjAyVODk9a9eoooAKKKKACqerapa6LpF3qd6+y2tYmlkPsBnA9z0FXKhurS2vrWS1u4Iri3lG2SKVAysPQg8GgDwn4S+Hf8AhO/FGr+P/EVqk6vcFbOKUbkD8c4PUIu1Rn37ivfKp6XpVjomnRafptrHbWkWfLijHC5JJ/UmrlABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAf/

**Comment by BadDeveloper2022** [comment]
我用了 第三种，第五种，第七种都不行

**Comment by by-syk** [comment]
这个项目是通过像素对比来识别的，仅支持列举出的几种，其他不支持
